### ISSUE TITLE
R200

### ISSUE THREAD

**Issue by siltemc** [vocong25/librealsense_for_arm#1]
Hi,

Not and actual issue.
Just wanted to let you know I was able to use this to get a R200 working on my Pi-4.
I could run the examples with no issues. 
Thank you for posting this online!

**Comment by congvm-cs** [comment]
@siltemc  It's so great to hear that. ;)

**Comment by congvm-cs** [comment]
@siltemc  I will update `README.md` that source code works on R200 as well. Thank you very much!

**Comment by siltemc** [comment]
Okay great!
